# Copyright (c) The mlkem-native project authors
# Copyright (c) The mldsa-native project authors
# SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

name: Extended
permissions:
  contents: read
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build_kat:
    strategy:
      fail-fast: false
      matrix:
        external:
         - ${{ github.repository_owner != 'pq-code-package' }}
        target:
         - runner: macos-latest
           name: 'MacOS (aarch64)'
           arch: mac
           mode: native
           nix_shell: ci
         - runner: macos-13
           name: 'MacOS (x86_64)'
           arch: mac
           mode: native
           nix_shell: ci
         - runner: pqcp-arm64
           name: 'ubuntu-latest (aarch64)'
           arch: aarch64
           mode: native
           nix_shell: ci
         - runner: pqcp-arm64
           name: 'ubuntu-latest (aarch64)'
           arch: x86_64
           mode: cross-x86_64
           nix_shell: ci-cross-x86_64
         - runner: pqcp-arm64
           name: 'ubuntu-latest (aarch64)'
           arch: riscv64
           mode: cross-riscv64
           nix_shell: ci-cross-riscv64
         - runner: pqcp-arm64
           name: 'ubuntu-latest (aarch64)'
           arch: riscv32
           mode: cross-riscv32
           nix_shell: ci-cross-riscv32
         - runner: pqcp-arm64
           name: 'ubuntu-latest (ppc64le)'
           arch: ppc64le
           mode: cross-ppc64le
           nix_shell: ci-cross-ppc64le
         - runner: pqcp-x64
           name: 'ubuntu-latest (x86_64)'
           arch: x86_64
           mode: native
           nix_shell: ci
         - runner: pqcp-x64
           name: 'ubuntu-latest (x86_64)'
           arch: aarch64
           mode: cross-aarch64
           nix_shell: ci-cross-aarch64
         - runner: pqcp-x64
           name: 'ubuntu-latest (x86_64)'
           arch: aarch64_be
           mode: cross-aarch64_be
           nix_shell: ci-cross-aarch64_be
        exclude:
          - {external: true,
             target: {
               runner: pqcp-arm64,
               name: 'ubuntu-latest (aarch64)',
               arch: aarch64,
               mode: native,
              nix_shell: ci
             }}
          - {external: true,
             target: {
               runner: pqcp-arm64,
               name: 'ubuntu-latest (aarch64)',
               arch: x86_64,
               mode: cross-x86_64,
               nix_shell: ci-cross-x86_64
             }}
          - {external: true,
             target: {
               runner: pqcp-arm64,
               name: 'ubuntu-latest (aarch64)',
               arch: riscv64,
               mode: cross-riscv64,
               nix_shell: ci-corss-riscv64
             }}
          - {external: true,
             target: {
               runner: pqcp-arm64,
               name: 'ubuntu-latest (aarch64)',
               arch: riscv32,
               mode: cross-riscv32,
               nix_shell: ci-cross-riscv32
             }}
          - {external: true,
             target: {
               runner: pqcp-arm64,
               name: 'ubuntu-latest (ppc64le)',
               arch: ppc64le,
               mode: cross-ppc64le,
               nix_shell: ci-cross-ppc64le
             }}
          - {external: true,
             target: {
               runner: pqcp-x64,
               name: 'ubuntu-latest (x86_64)',
               arch: x86_64,
               mode: native,
               nix_shell: ci
             }}
          - {external: true,
             target: {
               runner: pqcp-x64,
               name: 'ubuntu-latest (x86_64)',
               arch: aarch64,
               mode: cross-aarch64,
               nix_shell: ci-cross-aarch64
             }}
          - {external: true,
             target: {
               runner: pqcp-x64,
               name: 'ubuntu-latest (x86_64)',
               arch: aarch64_be,
               mode: cross-aarch64_be,
               nix_shell: ci-cross-aarch64_be
             }}
    name: Functional tests (${{ matrix.target.arch }}${{ matrix.target.mode != 'native' && ', cross' || ''}})
    runs-on: ${{ matrix.target.runner }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: build + test
        uses: ./.github/actions/multi-functest
        with:
          nix-shell: ${{ matrix.target.nix_shell }}
          nix-cache: ${{ matrix.target.mode == 'native' && 'false' || 'true' }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          compile_mode: ${{ matrix.target.mode }}
          # There is no native code yet on PPC64LE, R-V or AArch64_be, so no point running opt tests
          opt: ${{ (matrix.target.arch != 'ppc64le' && matrix.target.arch != 'riscv64' && matrix.target.arch != 'riscv32' && matrix.target.arch != 'aarch64_be') && 'all' || 'no_opt' }}
      - name: build + test (+debug+memsan+ubsan)
        uses: ./.github/actions/multi-functest
        if: ${{ matrix.target.mode == 'native' }}
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          compile_mode: native
          cflags: "-DMLDSA_DEBUG -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
  compiler_tests:
    name: Compiler tests  (${{ matrix.compiler.name }}, ${{ matrix.target.name }}, ${{ matrix.cflags }})
    strategy:
      fail-fast: false
      matrix:
        cflags: [ "-O0", "-Os", "-O3" ]
        target:
         - runner: pqcp-arm64
           name: 'aarch64'
         - runner: ubuntu-latest
           name: 'x86_64'
         - runner: macos-latest
           name: 'macos'
        compiler:
         - name: gcc-4.8
           shell: ci_gcc48
           darwin: False
           c17: False
           c23: False
           opt: all
           examples: False
         - name: gcc-4.9
           shell: ci_gcc49
           darwin: False
           c17: False
           c23: False
           opt: all
           examples: False
         - name: gcc-7
           shell: ci_gcc7
           darwin: False
           c17: False
           c23: False
           opt: all
           examples: False
         - name: gcc-11
           shell: ci_gcc11
           darwin: True
           c17: True
           c23: False
           opt: all
           examples: False
         - name: gcc-13
           shell: ci_gcc13
           darwin: True
           c17: True
           c23: False
           opt: all
           examples: False
         - name: gcc-14
           shell: ci_gcc14
           darwin: True
           c17: True
           c23: True
           opt: all
           examples: False
         - name: gcc-15
           shell: ci_gcc15
           # TODO: Add this once gcc15 is supported in nix on aarch64-Darwin
           darwin: False
           c17: True
           c23: True
           opt: all
           examples: true
         - name: clang-18
           shell: ci_clang18
           darwin: True
           c17: True
           c23: True
           opt: all
           examples: False
         - name: clang-19
           shell: ci_clang19
           darwin: True
           c17: True
           c23: True
           opt: all
           examples: False
         - name: clang-20
           shell: ci_clang20
           darwin: True
           c17: True
           c23: True
           opt: all
           examples: False
         - name: clang-21
           shell: ci_clang21
           darwin: True
           c17: True
           c23: True
           opt: all
           examples: False
         # CPU flags are not correctly passed to the zig assembler
         # https://github.com/ziglang/zig/issues/23576
         # We therefore only test the C backend
         #
         # We omit all examples since there is currently no way to run
         # only those examples not involving native code.
         - name: zig-0.12
           shell: ci_zig0_12
           darwin: True
           c17: True
           c23: False
           examples: False
           opt: no_opt
         - name: zig-0.13
           shell: ci_zig0_13
           darwin: True
           c17: True
           c23: False
           examples: False
           opt: no_opt
         - name: zig-0.14
           shell: ci_zig0_14
           darwin: True
           c17: True
           c23: True
           examples: False
           opt: no_opt
         - name: zig-0.15
           shell: ci_zig0_15
           darwin: True
           c17: True
           c23: True
           examples: False
           opt: no_opt
    runs-on: ${{ matrix.target.runner }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: native build+functest (default)
        if: ${{ matrix.compiler.darwin || matrix.target.runner != 'macos-latest' }}
        uses: ./.github/actions/multi-functest
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          compile_mode: native
          func: true
          kat: false
          acvp: false
          examples: ${{ matrix.compiler.examples }}
          opt: ${{ matrix.compiler.opt }}
          nix-shell: ${{ matrix.compiler.shell }}
          cflags: "${{ matrix.cflags }}"
      - name: native build+functest (C90)
        if: ${{ matrix.compiler.darwin || matrix.target.runner != 'macos-latest' }}
        uses: ./.github/actions/multi-functest
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          compile_mode: native
          func: true
          kat: false
          acvp: false
          examples: ${{ matrix.compiler.examples }}
          opt: ${{ matrix.compiler.opt }}
          nix-shell: ${{ matrix.compiler.shell }}
          cflags: "-std=c90 ${{ matrix.cflags }}"
      - name: native build+functest (C99)
        if: ${{ matrix.compiler.darwin || matrix.target.runner != 'macos-latest' }}
        uses: ./.github/actions/multi-functest
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          compile_mode: native
          func: true
          kat: false
          acvp: false
          examples: ${{ matrix.compiler.examples }}
          opt: ${{ matrix.compiler.opt }}
          nix-shell: ${{ matrix.compiler.shell }}
          cflags: "-std=c99 ${{ matrix.cflags }}"
      - name: native build+functest (C11)
        if: ${{ matrix.compiler.darwin || matrix.target.runner != 'macos-latest' }}
        uses: ./.github/actions/multi-functest
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          compile_mode: native
          func: true
          kat: false
          acvp: false
          examples: ${{ matrix.compiler.examples }}
          opt: ${{ matrix.compiler.opt }}
          nix-shell: ${{ matrix.compiler.shell }}
          cflags: "-std=c11 ${{ matrix.cflags }}"
      - name: native build+functest (C17)
        if: ${{ (matrix.compiler.darwin || matrix.target.runner != 'macos-latest') &&
                matrix.compiler.c17 }}
        uses: ./.github/actions/multi-functest
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          compile_mode: native
          func: true
          kat: false
          acvp: false
          examples: ${{ matrix.compiler.examples }}
          opt: ${{ matrix.compiler.opt }}
          nix-shell: ${{ matrix.compiler.shell }}
          cflags: "-std=c17 ${{ matrix.cflags }}"
      - name: native build+functest (C23)
        if: ${{ (matrix.compiler.darwin || matrix.target.runner != 'macos-latest') &&
                matrix.compiler.c23 }}
        uses: ./.github/actions/multi-functest
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          compile_mode: native
          func: true
          kat: false
          acvp: false
          examples: ${{ matrix.compiler.examples }}
          opt: ${{ matrix.compiler.opt }}
          nix-shell: ${{ matrix.compiler.shell }}
          cflags: "-std=c23 ${{ matrix.cflags }}"
  stack_analysis:
    name: Stack analysis (${{ matrix.target.name }}, ${{ matrix.cflags }})
    strategy:
      fail-fast: false
      matrix:
        external:
         - ${{ github.repository_owner != 'pq-code-package' }}
        target:
          - runner: pqcp-x64
            name: x86_64
          - runner: pqcp-arm64
            name: aarch64
        cflags: ['-O3', '-Os']
        exclude:
          - external: true
    runs-on: ${{ matrix.target.runner }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Stack analysis
        uses: ./.github/actions/multi-functest
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          compile_mode: native
          nix-shell: ci_valgrind-varlat_gcc15
          nix-cache: false
          opt: all
          cflags: "${{ matrix.cflags }}"
          func: false
          kat: false
          acvp: false
          examples: false
          stack: true
  config_variations:
    name: Non-standard configurations
    strategy:
      fail-fast: false
      matrix:
        external:
         - ${{ github.repository_owner != 'pq-code-package' }}
        target:
         - runner: pqcp-arm64
           name: 'ubuntu-latest (aarch64)'
         - runner: pqcp-x64
           name: 'ubuntu-latest (x86_64)'
        exclude:
          - {external: true,
             target: {
               runner: pqcp-arm64,
               name: 'ubuntu-latest (aarch64)',
             }}
          - {external: true,
             target: {
               runner: pqcp-x64,
               name: 'ubuntu-latest (x86_64)',
             }}
    runs-on: ${{ matrix.target.runner }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: "PCT enabled"
        uses: ./.github/actions/multi-functest
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          compile_mode: native
          cflags: "-DMLD_CONFIG_KEYGEN_PCT -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
          func: true
          kat: true
          acvp: true
      - name: "PCT enabled + broken"
        run: |
          make clean
          CFLAGS='-DMLD_CONFIG_FILE=\"../test/break_pct_config.h\"' make func -j4
          # PCT breakage is done at runtime via MLD_BREAK_PCT
          make run_func                 # Should be OK
          MLD_BREAK_PCT=0 make run_func # Should be OK
          if (MLD_BREAK_PCT=1 make run_func 2>&1 >/dev/null); then
             echo "PCT failure expected"
             exit 1
          else
             echo "PCT failed as expected"
          fi
      - name: "Custom zeroization (explicit_bzero)"
        uses: ./.github/actions/multi-functest
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          compile_mode: native
          cflags: "-std=c11 -D_GNU_SOURCE -DMLD_CONFIG_FILE=\\\\\\\"../test/custom_zeroize_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
          func: true
          kat: true
          acvp: true
          examples: false # Some examples use a custom config themselves
      - name: "No ASM"
        uses: ./.github/actions/multi-functest
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          compile_mode: native
          cflags: "-std=c11 -D_GNU_SOURCE -DMLD_CONFIG_FILE=\\\\\\\"../test/no_asm_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
          func: true
          kat: true
          acvp: true
          examples: false # Some examples use a custom config themselves
      - name: "Custom memcpy"
        uses: ./.github/actions/multi-functest
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          compile_mode: native
          cflags: "-std=c11 -D_GNU_SOURCE -DMLD_CONFIG_FILE=\\\\\\\"../test/custom_memcpy_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
          func: true
          kat: true
          acvp: true
          examples: false # Some examples use a custom config themselves
      - name: "Custom memset"
        uses: ./.github/actions/multi-functest
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          compile_mode: native
          cflags: "-std=c11 -D_GNU_SOURCE -DMLD_CONFIG_FILE=\\\\\\\"../test/custom_memset_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
          func: true
          kat: true
          acvp: true
          examples: false # Some examples use a custom config themselves
      - name: "Custom stdlib (memcpy + memset)"
        uses: ./.github/actions/multi-functest
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          compile_mode: native
          cflags: "-std=c11 -D_GNU_SOURCE -DMLD_CONFIG_FILE=\\\\\\\"../test/custom_stdlib_config.h\\\\\\\" -fsanitize=address -fsanitize=undefined -fno-sanitize-recover=all"
          func: true
          kat: true
          acvp: true
          examples: false # Some examples use a custom config themselves
  check_autogenerated_files:
    strategy:
      fail-fast: false
      matrix:
        system: [ubuntu-latest, pqcp-arm64]
    runs-on: ${{ matrix.system }}
    name: Check autogenerated files
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/setup-shell
        with:
          nix-shell: 'ci'
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            python3 ./scripts/autogen --dry-run
