# Copyright (c) The mldsa-native project authors
# SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT

name: Isabelle proofs
permissions:
  contents: read
on:
  workflow_call:
  workflow_dispatch:

jobs:
  compress:
    runs-on: ubuntu-latest
    container: makarius/isabelle:Isabelle2025-1
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build Compress session
        run: /home/isabelle/Isabelle/bin/isabelle build -D proofs/isabelle/compress
